INSERT INTO staging_table (
    DATE_BOOKED, ORIGIN, DESTINATION, ORDER_REF, TICKET_NO, SEATNO,
    DATE_REDEEMED, EMAIL, MOBILENO, FARE, CONVENIENCE_FEE, DISCOUNT,
    DEPARTURE_DATE, DEPARTURE_TIME, BUS_TYPE, NUMBER_OF_VOUCHERS_BOOKED,
    BOOK_DT, BOOK_TM, DEPARTURE_DAY, BOOKING_INFO, VOUCHER, ROUTE,
    TRIP_ID, TRIP_ID_DAY, REDEEMED_FLAG
)
SELECT
	DATE_BOOKED,
    ORIGIN, DESTINATION, ORDER_REF, TICKET_NO, SEATNO,
    DATE_REDEEMED, EMAIL, MOBILENO, 
    NULLIF(FARE, '') AS FARE,
    NULLIF(CONVENIENCE_FEE, '') AS CONVENIENCE_FEE,
    DISCOUNT,
	DEPARTURE_DATE,
-- Direct extraction of DEPARTURE_TIME from DEPARTURE_DATE
    CASE
        WHEN DEPARTURE_TIME LIKE '%PM' OR DEPARTURE_TIME LIKE '%AM' 
            THEN TIME_FORMAT(STR_TO_DATE(DEPARTURE_TIME, '%r'), '%H:%i:%s')
        WHEN LENGTH(DEPARTURE_TIME) = 8 AND DEPARTURE_TIME LIKE '%:%:%' 
            THEN TIME_FORMAT(STR_TO_DATE(DEPARTURE_TIME, '%H:%i:%s'), '%H:%i:%s')
        WHEN LENGTH(DEPARTURE_TIME) = 7 AND DEPARTURE_TIME LIKE '%:%:%' 
            THEN TIME_FORMAT(STR_TO_DATE(DEPARTURE_TIME, '%H:%i:%s'), '%H:%i:%s')
        WHEN LENGTH(DEPARTURE_TIME) = 5 AND DEPARTURE_TIME LIKE '%:%' 
            THEN TIME_FORMAT(STR_TO_DATE(CONCAT(DEPARTURE_TIME, ':00'), '%H:%i:%s'), '%H:%i:%s')
        ELSE NULL
    END AS DEPARTURE_TIME,
    BUS_TYPE, NUMBER_OF_VOUCHERS_BOOKED,
    NULL AS BOOK_DT,
    NULL AS BOOK_TM,
    NULL AS DEPARTURE_DAY,
    NULL AS BOOKING_INFO,
    NULL AS VOUCHER,
    NULL AS ROUTE,
    NULL AS TRIP_ID,
    NULL AS TRIP_ID_DAY,
    NULL AS REDEEMED_FLAG
FROM source_table;