DROP TABLE IF EXISTS source_table;
DROP TABLE IF EXISTS staging_table;
DROP TABLE IF EXISTS analytical_business_table;

CREATE TABLE source_table (
    DATE_BOOKED VARCHAR(255),
    ORIGIN VARCHAR(255),
    DESTINATION VARCHAR(255),
    ORDER_REF VARCHAR(255),
    TICKET_NO VARCHAR(255),
    SEATNO VARCHAR(255),
    DATE_REDEEMED VARCHAR(255),
    EMAIL VARCHAR(255),
    MOBILENO VARCHAR(255),
    FARE VARCHAR(255),
    CONVENIENCE_FEE VARCHAR(255),
    DISCOUNT VARCHAR(255),
    DEPARTURE_DATE VARCHAR(255),
    DEPARTURE_TIME VARCHAR(255),
    BUS_TYPE VARCHAR(255),
    NUMBER_OF_VOUCHERS_BOOKED VARCHAR(255)
); 


CREATE TABLE Analytical_Business_Table (

    DATE_BOOKED VARCHAR(255),
    ORIGIN VARCHAR(255),
    DESTINATION VARCHAR(255),
    ORDER_REF VARCHAR(255),
    TICKET_NO VARCHAR(255),
    SEATNO DECIMAL(10, 2),
    DATE_REDEEMED VARCHAR(255),
    EMAIL VARCHAR(255),
    MOBILENO VARCHAR(255),
    FARE DECIMAL(10, 2),
    CONVENIENCE_FEE DECIMAL(10, 2),
    DISCOUNT VARCHAR(255),
    DEPARTURE_DATE VARCHAR(255),
    DEPARTURE_TIME TIME,
    BUS_TYPE VARCHAR(255),
    NUMBER_OF_VOUCHERS_BOOKED VARCHAR(255),
    BOOK_DT DATE,
    BOOK_TM TIME,
    DEPARTURE_DAY VARCHAR(255),
    BOOKING_INFO VARCHAR(255),
    VOUCHER VARCHAR(255),
    ROUTE VARCHAR(255),
    TRIP_ID VARCHAR(255),
    TRIP_ID_DAY VARCHAR(255),
    REDEEMED_FLAG VARCHAR(255)
);


CREATE TABLE staging_table (
    DATE_BOOKED VARCHAR(255),
    ORIGIN VARCHAR(255),
    DESTINATION VARCHAR(255),
    ORDER_REF VARCHAR(255),
    TICKET_NO VARCHAR(255),
    SEATNO DECIMAL(10, 2),
    DATE_REDEEMED VARCHAR(255),
    EMAIL VARCHAR(255),
    MOBILENO VARCHAR(255),
    FARE DECIMAL(10, 2),
    CONVENIENCE_FEE DECIMAL(10, 2),
    DISCOUNT VARCHAR(255),
    DEPARTURE_DATE VARCHAR(255),
    DEPARTURE_TIME TIME,
    BUS_TYPE VARCHAR(255),
    NUMBER_OF_VOUCHERS_BOOKED VARCHAR(255),
    BOOK_DT DATE,
    BOOK_TM TIME,
    DEPARTURE_DAY VARCHAR(255),
    BOOKING_INFO VARCHAR(255),
    VOUCHER VARCHAR(255),
    ROUTE VARCHAR(255),
    TRIP_ID VARCHAR(255),
    TRIP_ID_DAY VARCHAR(255),
    REDEEMED_FLAG VARCHAR(255)
);

